sudo: false
cache: yarn

jobs:
  include:
    - stage: tests
      # script: yarn test
      script: echo "Tests"
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: hashtag-tracking
        api_key: $HEROKU_AUTH_TOKEN
        on: master
    - stage: test deploy
      script: 'curl http://hashtag-tracking.herokuapp.com'
