sudo: false
language: node_js
node_js: "8"
cache: yarn

jobs:
  include:
    - stage: tests
      # before_script:
      #   - yarn
      script: yarn test
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: hashtag-tracking
        api_key: $HEROKU_AUTH_TOKEN
        on: master
    - stage: test deploy
      script: 'curl http://hashtag-tracking.herokuapp.com'
